# Generated by Django 4.1 on 2022-09-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
