# Generated by Django 4.1 on 2022-09-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurements_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurements',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
